v {xschem version=3.4.5 file_version=1.2
}
G {}
K {}
V {}
S {}
E {}
T {CACE testbench voltage_out} -390 -640 0 0 0.6 0.6 {}
N 210 -260 210 -180 {
lab=dvdd}
N 150 -280 150 -250 {
lab=ena}
N 100 -300 100 -180 {
lab=avss}
N -10 -320 -10 -180 {
lab=avdd}
N -10 -120 -10 -80 {
lab=VSUB}
N -10 -80 320 -80 {
lab=VSUB}
N 320 -120 320 -80 {
lab=VSUB}
N 210 -120 210 -80 {
lab=VSUB}
N 150 -190 150 -80 {
lab=VSUB}
N 100 -120 100 -80 {
lab=VSUB}
N 320 -80 720 -80 {
lab=VSUB}
N 650 -290 690 -290 {
lab=out}
N 690 -290 690 -210 {
lab=out}
N 690 -150 690 -80 {
lab=VSUB}
N 320 -320 320 -180 {
lab=dvss}
N 430 -120 430 -80 {
lab=VSUB}
N 430 -210 430 -180 {
lab=vref}
C {devices/lab_pin.sym} -10 -80 0 0 {name=p1 sig_type=std_logic lab=VSUB}
C {devices/vsource.sym} 150 -220 0 0 {name=Vena value="DC [\{ena\} * \{Vdvdd\}]" savecurrent=false}
C {devices/vsource.sym} 100 -150 0 0 {name=Vvss value="DC \{Vvss\}" savecurrent=false}
C {devices/vsource.sym} -10 -150 0 0 {name=Vvdd value="DC \{Vvdd\}" savecurrent=false}
C {devices/code_shown.sym} -1010 -280 0 0 {name=CONTROL only_toplevel=false value=".control
** Find voltage output as a DC operating point.  Set input differential
** to some value for calculating Voh or Vol.
save out
op
let vtest = v(out)
set wr_singlescale
echo $&vtest > \{simpath\}/\{filename\}_\{N\}.data
quit
.endc
"}
C {devices/code_shown.sym} -1000 -580 0 0 {name=SETUP only_toplevel=false value="* CACE gensim simulation file \{filename\}_\{N\}
* Generated by CACE gensim, Efabless Corporation (c) 2023
* Find the current through the amplifier under condition of static input

.include \{DUT_path\}

.lib \{PDK_ROOT\}/\{PDK\}/libs.tech/combined/sky130.lib.spice \{corner\}

.option TEMP=\{temperature\}
* Flag unsafe operating conditions (exceeds models' specified limits)
.option warn=1
"}
C {devices/res.sym} 300 -50 0 0 {name=RSUB
value=0.01
device=resistor}
C {devices/gnd.sym} 300 -20 0 0 {name=l1 lab=GND}
C {devices/vsource.sym} 210 -150 0 0 {name=Vdvdd value="DC \{Vdvdd\}" savecurrent=false}
C {devices/vsource.sym} 320 -150 0 0 {name=Vdvss value="DC \{Vdvss\}" savecurrent=false}
C {devices/lab_pin.sym} -10 -320 0 0 {name=p2 sig_type=std_logic lab=avdd}
C {devices/lab_pin.sym} 690 -290 0 1 {name=p4 sig_type=std_logic lab=out}
C {sky130_am_ip__ldo_01v8.sym} 570 -290 0 0 {name=x1}
C {devices/lab_pin.sym} 480 -310 0 0 {name=p5 sig_type=std_logic lab=avdd}
C {devices/lab_pin.sym} 480 -290 0 0 {name=p6 sig_type=std_logic lab=avss}
C {devices/lab_pin.sym} 480 -270 0 0 {name=p7 sig_type=std_logic lab=vref}
C {devices/lab_pin.sym} 550 -240 0 0 {name=p8 sig_type=std_logic lab=ena}
C {devices/lab_pin.sym} 550 -220 0 0 {name=p9 sig_type=std_logic lab=dvdd}
C {devices/lab_pin.sym} 550 -200 0 0 {name=p10 sig_type=std_logic lab=dvss}
C {devices/res.sym} 690 -180 0 0 {name=R1
value=\{Rload\}
footprint=1206
device=resistor
m=1}
C {devices/lab_pin.sym} 100 -300 0 0 {name=p11 sig_type=std_logic lab=avss}
C {devices/lab_pin.sym} 150 -280 0 0 {name=p12 sig_type=std_logic lab=ena}
C {devices/lab_pin.sym} 210 -260 0 0 {name=p13 sig_type=std_logic lab=dvdd}
C {devices/lab_pin.sym} 320 -300 0 0 {name=p14 sig_type=std_logic lab=dvss}
C {devices/vsource.sym} 430 -150 0 0 {name=Vdvss1 value="DC \{Vref\}" savecurrent=false}
C {devices/lab_pin.sym} 430 -210 0 0 {name=p3 sig_type=std_logic lab=vref}
